#!/usr/bin/env bash
# Install the templated systemd unit that runs one IB Gateway per broker
# connection: ibkr-gateway@<connection id>.service.
#
# The unit body is generated by app.provisioning.write_unit_template() rather
# than kept as a second copy here, so the file systemd loads and the file the
# API would write can never drift apart. The API installs it on its own the
# first time a connection is provisioned; run this when you would rather have
# it in place beforehand, or after changing GATEWAY_INSTANCE_ROOT.
#
#   sudo deploy/install-gateway-template.sh [/path/to/backend]
set -euo pipefail

BACKEND="${1:-$(cd "$(dirname "$0")/../backend" && pwd)}"
PYTHON="${PYTHON:-$BACKEND/.venv/bin/python}"

if [[ ! -x "$PYTHON" ]]; then
  echo "No Python at $PYTHON. Pass the backend directory, or set PYTHON." >&2
  exit 1
fi

cd "$BACKEND"
UNIT=$("$PYTHON" -c 'from app.provisioning import write_unit_template; print(write_unit_template())')
echo "Wrote $UNIT"

systemctl daemon-reload
echo "Reloaded systemd."
echo
echo "Nothing is started: a connection's gateway starts when an operator starts it"
echo "from the dashboard, or with 'systemctl start ibkr-gateway@<connection id>'."
echo "Starting a live gateway performs a real IBKR login."
